<?php
/**
 * Created by PhpStorm.
 * User: Mila
 * Date: 20/11/2018
 * Time: 10:16
 */


namespace BoutiqueBundle\Repository;

/**
 * MembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
