<?php
/**
 * Created by PhpStorm.
 * User: Mila
 * Date: 20/11/2018
 * Time: 10:13
 */


namespace BoutiqueBundle\Repository;

/**
 * MembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailsCommandeRepository extends \Doctrine\ORM\EntityRepository
{
    /*
     * si j'ai des requêtes qui concernent exclusivement la table produit, et qui sont spécifiques... je vais les coder ici plutôt que de la faire dans le
     * controller
     * cela maintient un controller plus clair et plus générique
     */


}
